name: TESTS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'  # Cambia la versión según tus necesidades

    - name: Build and Test with Maven
      run: mvn clean test

